


  <?php include('header_admin.php'); ?>
  
   <link href="https://cdn.datatables.net/1.10.10/css/dataTables.bootstrap.min.css" rel="stylesheet" type="text/css" />
     
      
     <script src="https://cdn.datatables.net/1.10.10/js/jquery.dataTables.min.js"></script>
      <script src="https://cdn.datatables.net/1.10.10/js/dataTables.bootstrap.min.js"></script>
      
 <script>
 
 $(document).ready(function() {
    $('#example').DataTable();
} );
 </script>
 
          <?php include('sidebar_admin.php'); ?>

            <!-- top navigation -->
            <div class="top_nav">

                <?php include('header_nav_admin.php'); ?>
			
			</div>
            <!-- /top navigation -->

            <!-- page content -->
            <div class="right_col" role="main">
                <div class="">
                    <div class="page-title">
                        <div class="title_left">
                            <h3>
                  Manage Instagram
                   
                </h3>
                        </div>

                        <div class="title_right">
     
                        </div>
                    </div>
                    <div class="clearfix"></div>

                    <div class="row">

                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <div class="x_panel">
                                <div class="x_title">
                                    <h2> Manage Instagram  </h2>
                               
                                    <div class="clearfix"></div>
                                </div>
                                
                                
                                <div class="x_content">                                 
                                 <table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
										<thead>
											<tr>
												
												  <th>Instagram  Images</th>  
											</tr>
										</thead>
										<tfoot>
											<tr>
												
												 <th>Instagram  Images</th>                              
                                               
											</tr>
										</tfoot>
										<tbody>
										<?php
											 
											 /*  Generated By Me 
											 CLIENT ID	49d1d7e0bec94e3fbbdd7b07041e54b6
												CLIENT SECRET	87117eb307834fb9b770ff5d637945a7
												WEBSITE URL	http://www.oremtechnologies.com/abhishek/hotel/
												REDIRECT URI	http://122.160.233.58/abhi/coffee-shop/adminpanel/instagram1.php 
												*/
											  
											  
											  /* Auto Generated Generated By Me 
											    auto genrate Client ID:-   2275375072
											    token Key:-    2275375072.ab103e5.2a9165d63bc74149b2129e62bad01a13
											    https://api.instagram.com/v1/users/2275375072/media/recent/?access_token=2275375072.ab103e5.2a9165d63bc74149b2129e62bad01a13 
											  */
											  $result = 'https://api.instagram.com/v1/users/2275375072/media/recent/?access_token=2275375072.ab103e5.2a9165d63bc74149b2129e62bad01a13';
												$instagram_json = file_get_contents($result);
											  $results = json_decode($instagram_json, true);
											 
											 $a = 0;
											  	 foreach ($results['data'] as $getData) {
										 		if($a==2){
										 		break;
										 		}	else{
										 		$a++;
										 		}	
										 		$instagram_images =	$getData['images']['thumbnail']['url'] ;	
										 			
										 			 ?>
											<tr>
											
											<td> <img class="insta-image" src="<?php echo $instagram_images; ?>">
											</td> 

											</tr>
										<?php }	?>
										</tbody>
									</table>
                                 
                                 </div>
                            </div>
                        </div>

                        <br />
                        <br />
                        <br />

                    </div>
                </div>
                
          <?php include('footer_admin.php'); ?>
          
        